# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myers_diff_cpp <- function(a, b, max_edit_length = 0, timeout_ms = 0) {
    .Call(`_jsdiffr_myers_diff_cpp`, a, b, max_edit_length, timeout_ms)
}

