suppressMessages(pkgload::load_all("c:/Users/kyleh/GitHub/anthropic_diff/jsdiffr", quiet = TRUE))
show <- function(lbl, d) { cat("---", lbl, "---\n"); print(as.data.frame(d)) }
show("words", diff_words("The quick brown fox", "The slow brown fox"))
show("words_with_space", diff_words_with_space("a b  c", "a  b c"))
show("sentences", diff_sentences("Hello world. Foo bar.", "Hello world. Baz bar."))
show("css", diff_css("a{color:red;}", "a{color:blue;}"))
d <- diff_arrays(c("a", "b", "c"), c("a", "c", "d"))
cat("--- arrays ---\n"); print(d$added); str(d$value)
show("json", diff_json(list(a = 1, b = 2), list(a = 1, b = 3)))
cat("--- create_patch ---\n")
cat(create_patch("f.txt", "a\nb\nc\n", "a\nB\nc\n"))
cat("--- roundtrip apply ---\n")
p <- create_patch("f.txt", "a\nb\nc\n", "a\nB\nc\n")
cat("applied identical:", identical(apply_patch("a\nb\nc\n", p), "a\nB\nc\n"), "\n")
