// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// myers_diff_cpp
SEXP myers_diff_cpp(IntegerVector a, IntegerVector b, double max_edit_length, double timeout_ms);
RcppExport SEXP _jsdiffr_myers_diff_cpp(SEXP aSEXP, SEXP bSEXP, SEXP max_edit_lengthSEXP, SEXP timeout_msSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type max_edit_length(max_edit_lengthSEXP);
    Rcpp::traits::input_parameter< double >::type timeout_ms(timeout_msSEXP);
    rcpp_result_gen = Rcpp::wrap(myers_diff_cpp(a, b, max_edit_length, timeout_ms));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jsdiffr_myers_diff_cpp", (DL_FUNC) &_jsdiffr_myers_diff_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_jsdiffr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
